alias gt='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'
alias gp='git push'
alias gpo='git push origin'
alias srd='sudo rm -r'
alias s='sudo'
alias gcma='git commit -m -a'
alias ce='cd ~/.emacs.d'
alias cei='cd ~/.emacs.d/init.d/'
alias cee='cd ~/.emacs.d/elpa/'
alias ceg='cd ~/.emacs.d/el-get/'
alias cy='cd ~/gh/yefeiyu.github.io'
alias ca='cd ~/gh/yefeiyu.github.io/_app/'
alias caa='cd ~/gh/yefeiyu.github.io/_app/_data/'
alias cad='cd ~/gh/yefeiyu.github.io/_app/_drafts/'
alias cai='cd ~/gh/yefeiyu.github.io/_app/_includes/'
alias cal='cd ~/gh/yefeiyu.github.io/_app/_layouts/'
alias cao='cd ~/gh/yefeiyu.github.io/_app/_org/'
alias cam='cd ~/gh/yefeiyu.github.io/_app/_md/'
alias cag='cd ~/gh/yefeiyu.github.io/_app/_pages/'
alias cap='cd ~/gh/yefeiyu.github.io/_app/_posts/'
alias can='cd ~/gh/yefeiyu.github.io/_app/_plugins/'
alias cs='cd ~/gh/yefeiyu.github.io/_site/'
alias cprs='cp -r  ~/gh/yefeiyu.github.io/_site/* ~/gh/yefeiyu.github.io/ '

alias js='jekyll serve'
alias gs='grunt serve'
alias bl='bash --login'
alias lsfa='ls -Fa'
alias gapm='ga . && gcma . && gpo master'
alias xmd='xmodmap ~/.Xmodmaprc'

alias rgs='sudo rm -r ~/gh/yefeiyu.github.io/_site 404.html email fu robots.txt about email-signup index.html search apple-touch-icon.png favicon.ico it sitemap.xml archives favicon.svg life soft art feed.json mobile tags assets feed.xml news zza attitude fiction review && grunt serve'
#&& sudo rm -r  ~/gh/yefeiyu.github.io/about && sudo rm -r ~/gh/yefeiyu.github.io/art && sudo rm -r ~/gh/yefeiyu.github.io/email* && sudo rm -r ~/gh/yefeiyu.github.io/fu && sudo rm -r ~/gh/yefeiyu.github.io/it && sudo rm -r ~/gh/yefeiyu.github.io/life && sudo rm -r ~/gh/yefeiyu.github.io/news && sudo rm ~/gh/yefeiyu.github.io/*.html && sudo rm *.txt 
alias rjs='sudo rm -r ~/gh/yefeiyu.github.io/_site && sudo rm ~/gh/yefeiyu.github.io/*.html && jekyll serve'
alias cgm='cp -r  _site/* . && git add . && git commit -m -a . && git push origin master'

alias got='git '
alias get='git '

alias ec='emacsclient'
alias sec='sudo emacsclient'
##;;alias lsd='ls ~/gh/yefeiyu.github.io/_app/_drafts/'
##alias mvd='mv ~/gh/yefeiyu.github.io/_app/_drafts/*'
##alias mvda='mv ~/gh/yefeiyu.github.io/_app/_drafts/'
##alias cmp='mv ~/gh/yefeiyu.github.io/_app/_org/* ~/gh/yefeiyu.github.io/org/ && cd ~/gh/yefeiyu.github.io/_app/_posts/ && cp ~/gh/yefeiyu.github.io/_app/_drafts/*.md ~/gh/yefeiyu.github.io/_app/_posts'
##alias rmd='rm ~/gh/yefeiyu.github.io/_app/_drafts/* && cd ~/gh/yefeiyu.github.io/'

alias cdp='cd ~/gh/yefeiyu.github.io/_app/_posts/ && cp ~/gh/yefeiyu.github.io/_app/_drafts/*.html ~/gh/yefeiyu.github.io/_app/_posts'
alias rmd='rm ~/gh/yefeiyu.github.io/_app/_drafts/* && cd ~/gh/yefeiyu.github.io/'

alias cdd='cd ~/download'
alias caii='cd ~/gh/yefeiyu.github.io/_app/_includes/themes/curtana/includes'
alias cail='cd ~/gh/yefeiyu.github.io/_app/_includes/themes/curtana/layouts'
alias cas='cd ~/gh/yefeiyu.github.io/_app/assets/'
alias casj='cd ~/gh/yefeiyu.github.io/_app/assets/themes/curtana/_js'
alias casl='cd ~/gh/yefeiyu.github.io/_app/assets/themes/curtana/_less'
alias cb='cd ~/gh/yefeiyu.github.io/_amsf/core/_app/'
alias cbs='cd ~/gh/yefeiyu.github.io/_amsf/core/_app/assets'
alias cbsj='cd ~/gh/yefeiyu.github.io/_amsf/core/_app/assets/themes/curtana/_js'
alias cbsl='cd ~/gh/yefeiyu.github.io/_amsf/core/_app/assets/themes/curtana/_less'

alias cpl='cd ~/gh/yefeiyu.github.io/_app/_posts/life/'
alias cps='cd ~/gh/yefeiyu.github.io/_app/_posts/soft/'
alias cpa='cd ~/gh/yefeiyu.github.io/_app/_posts/act/'
alias cpf='cd ~/gh/yefeiyu.github.io/_app/_posts/fiction/'
alias cpo='cd ~/gh/yefeiyu.github.io/_app/_posts/love/'
alias cpm='cd ~/gh/yefeiyu.github.io/_app/_posts/memo/'
alias cpr='cd ~/gh/yefeiyu.github.io/_app/_posts/reader/'
alias cpv='cd ~/gh/yefeiyu.github.io/_app/_posts/review/'
alias cpz='cd ~/gh/yefeiyu.github.io/_app/_posts/zza/'
alias cpzl='cd ~/gh/yefeiyu.github.io/_app/_posts/zzl/'
alias rmf='sudo rm -rf'
# alias cid='cp /home/xx/Dropbox/ygi/md/* ~/gh/yefeiyu.github.io/_app/_drafts/ && cd ~/gh/yefeiyu.github.io/_app/_drafts/'
alias cod='cp ~/gh/yefeiyu.github.io/_app/_org/*.md ~/gh/yefeiyu.github.io/_app/_drafts/ && cd ~/gh/yefeiyu.github.io/_app/_drafts/'
alias eba='e ~/.bash_aliases'
alias sba='source ~/.bash_aliases'
alias cdr='cd ~/Dropbox'
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
#use ec as alias for emacs client
alias e='emacsclient -t -a "" $*'
#use emacs as default editor
export EDITOR="e"

alias edu='e ~/Dropbox/log-usr'
alias sas='sudo apt-cache search'
alias sai='sudo apt-get install'
alias sar='sudo apt-get remove'
alias saar='sudo apt-get autoremove'
alias saug='sudo apt-get upgrade'
alias sap='sudo apt-get purge'
alias sau='sudo apt-get update'
alias sac='sudo apt-get clean'
alias saac='sudo apt-get autoclean'

##bak

alias cby='cd ~/gh/bak.yefeiyu.github.io'
alias cba='cd ~/gh/bak.yefeiyu.github.io/_app/'
alias cbaa='cd ~/gh/bak.yefeiyu.github.io/_app/_data/'
alias cbad='cd ~/gh/bak.yefeiyu.github.io/_app/_drafts/'
alias cbai='cd ~/gh/bak.yefeiyu.github.io/_app/_includes/'
alias cbal='cd ~/gh/bak.yefeiyu.github.io/_app/_layouts/'
alias cbao='cd ~/gh/bak.yefeiyu.github.io/_app/_org/'
alias cbam='cd ~/gh/bak.yefeiyu.github.io/_app/_md/'
alias cbag='cd ~/gh/bak.yefeiyu.github.io/_app/_pages/'
alias cbap='cd ~/gh/bak.yefeiyu.github.io/_app/_posts/'
alias cbs='cd ~/gh/bak.yefeiyu.github.io/_site/'
alias cbprs='cp -r  ~/gh/bak.yefeiyu.github.io/_site/* ~/gh/bak.yefeiyu.github.io/ '

alias cbdp='cd ~/gh/bak.yefeiyu.github.io/_app/_posts/ && cp ~/gh/bak.yefeiyu.github.io/_app/_drafts/*.html ~/gh/bak.yefeiyu.github.io/_app/_posts'

alias cbdd='cd ~/download'
alias cbaii='cd ~/gh/bak.yefeiyu.github.io/_app/_includes/themes/curtana/includes'
alias cbail='cd ~/gh/bak.yefeiyu.github.io/_app/_includes/themes/curtana/layouts'
alias cbas='cd ~/gh/bak.yefeiyu.github.io/_app/assets/'
alias cbasj='cd ~/gh/bak.yefeiyu.github.io/_app/assets/themes/curtana/_js'
alias cbasl='cd ~/gh/bak.yefeiyu.github.io/_app/assets/themes/curtana/_less'
alias cbb='cd ~/gh/bak.yefeiyu.github.io/_amsf/core/_app/'
alias cbbs='cd ~/gh/bak.yefeiyu.github.io/_amsf/core/_app/assets'
alias cbbsj='cd ~/gh/bak.yefeiyu.github.io/_amsf/core/_app/assets/themes/curtana/_js'
alias cbbsl='cd ~/gh/bak.yefeiyu.github.io/_amsf/core/_app/assets/themes/curtana/_less'

alias cbpl='cd ~/gh/bak.yefeiyu.github.io/_app/_posts/life/'
alias cbps='cd ~/gh/bak.yefeiyu.github.io/_app/_posts/soft/'
alias cbpa='cd ~/gh/bak.yefeiyu.github.io/_app/_posts/act/'
alias cbpf='cd ~/gh/bak.yefeiyu.github.io/_app/_posts/fiction/'
alias cbpo='cd ~/gh/bak.yefeiyu.github.io/_app/_posts/love/'
alias cbpm='cd ~/gh/bak.yefeiyu.github.io/_app/_posts/memo/'
alias cbpr='cd ~/gh/bak.yefeiyu.github.io/_app/_posts/reader/'
alias cbpv='cd ~/gh/bak.yefeiyu.github.io/_app/_posts/review/'
alias cbpz='cd ~/gh/bak.yefeiyu.github.io/_app/_posts/zza/'
alias cbpzl='cd ~/gh/bak.yefeiyu.github.io/_app/_posts/zzl/'
alias cbod='cp ~/gh/bak.yefeiyu.github.io/_app/_org/*.md ~/gh/bak.yefeiyu.github.io/_app/_drafts/ && cd ~/gh/bak.yefeiyu.github.io/_app/_drafts/'

alias cswp='cd ~/gh/sparanoid.com/_app/_posts/work/project'
alias cswc='cd ~/gh/sparanoid.com/_app/_posts/work/commercial'

alias	 cg='cd ~/gh'
alias ecy='e _config.yml'
alias px='proxychains4'
alias rgl='rm Gemfile.lock'
alias egf='e Gemfile'
alias epj='e package.json'
alias egc='e Gruntfile.coffee'
alias fnd='sudo find / -name'
alias bi='bundle install'
alias sbi='sudo bundle install'
alias ni='npm install'
alias bui='bundle uninstall'
alias sbui='sudo bundle uninstall'
alias nui='npm uninstall'
alias sni='sudo npm install'
alias snui='sudo npm uninstall'
alias gi='gem install'
alias gui='gem uninstall'
alias sgi='sudo gem install'
alias sgui='sudo gem uninstall'
alias bu='bundle update'
alias nu='npm update'
alias smi='sudo make install'

alias scr='sudo cp -r'
alias cr='cp -r'
alias srb='sudo reboot'
alias sht='sudo halt'
alias xmd='xmodmap ~/.xmodmaprc'
alias aak='ALGOLIA_API_KEY='0d3b9dd8d051e8bb0de1af01012c3ad4' bundle exec jekyll algolia'
alias dr='winpty docker run -it -p 4321:4321 -v /d/cygwin64/home/xx/gh/yefeiyu.github.io/:/home/xx/gh/yefeiyu.github.io/ xxmm/ruby-node-grunt:v1'