# Site settings
title: y.g.i
description: "无为"
url: "https://yefeiyu2.github.io"

# Secondary Parameters
baseurl: "/yefeiyu"
header-img: ⁨img/home-bg.jpg
headercolor: "#FFFFFF"
logo: ⁨_app/⁨assets/img⁩/apple-touch-icon.png

